version: "3.9"
services:
  rocketmq-namesrv:
    image: apache/rocketmq:${ROCKETMQ_VERSION}
    restart: always
    container_name: rocketmq-namesrv
      # environment:
      #   JAVA_OPT_EXT: "-server -Xms64m -Xmx64m -Xmn64m"
    volumes:
      # 映射本地目录权限一定要设置为 777 权限，否则启动不成功
      - rocketmq_namesrv_logs:/home/rocketmq/logs
    networks:
      - rocketmq
    ports:
      - 9876:9876
    command: sh mqnamesrv
  rocketmq-broker:
    image: apache/rocketmq:${ROCKETMQ_VERSION}
    user: root
    # restart: always
    container_name: rocketmq-broker
    volumes:
      # 映射本地目录权限一定要设置为 777 权限，否则启动不成功
      - rocketmq_broker_logs:/home/rocketmq/logs
      - rocketmq_broker_data:/home/rocketmq/store
      - ./broker.conf:/home/rocketmq-${ROCKETMQ_VERSION}/conf/broker.conf
    environment:
      - NAMESRV_ADDR=rocketmq-namesrv:9876
      # - JAVA_OPTS:=-Duser.home=/opt
      - JAVA_OPT_EXT=-server -Xms64m -Xmx64m -Xmn64m
    depends_on:
      - rocketmq-namesrv
    networks:
      - rocketmq
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    command: sh mqbroker -c /home/rocketmq-${ROCKETMQ_VERSION}/conf/broker.conf
  rmqdashboard:
    image: apacherocketmq/rocketmq-dashboard:${ROCKETMQ_DASHBOARD_VERSION}
    restart: always
    container_name: rocketmq-dashboard
    environment:
      - JAVA_OPTS=-Drocketmq.config.namesrvAddr=rocketmq-namesrv:9876 -Dserver.port=8180 -Drocketmq.config.isVIPChannel=false
      # - JAVA_OPT_EXT=-Xms128m -Xmx128m -Xmn128m
    depends_on:
      - rocketmq-namesrv
    networks:
      - rocketmq
    ports:
      - 8180:8180

networks:
  rocketmq:
    driver: bridge

volumes:
  rocketmq_namesrv_logs:
    name: rocketmq_namesrv_logs
  rocketmq_broker_data:
    name: rocketmq_broker_data
  rocketmq_broker_logs:
    name: rocketmq_broker_logs